### ISSUE TITLE
Too many projects blocks creating a new project option

### ISSUE THREAD

**Issue by alsiu7** [Purplecannon/footnote#70]
Summary: (Bug?)
When there are too many projects, the scroll bar does not scroll all the way back for the user to create a new project.

Component:
Frontend pages (Home page)

Version:
Beta release

Device, OS, Browser:
Surface 7, Windows 10, Chrome

Description:
After creating 4 new projects and then going back to the project home page, there is a scroll bar to scroll through the projects. However, the create new project option box is too far on the left and the scroll bar does not reach it. (Not sure if it's intended for users to have a max of 4 projects.)

**Comment by miahuynhh** [comment]
Thank you for pointing this out! We are fixing the UI so that it wraps at 4 projects per row, and then the projects after that will fill up a lower row.

**Comment by Purplecannon** [comment]
Addressed
